services:
  - type: web
    name: foodie-express-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        value: mongodb+srv://pankajschauhan0592:pankaj809080@cluster.mongodb.net/foodie-express?retryWrites=true&w=majority&appName=Cluster0
      - key: JWT_SECRET
        value: foodie-express-super-secure-jwt-secret-2024-production
      - key: JWT_EXPIRE
        value: 7d
      - key: FRONTEND_URL
        value: https://your-frontend-domain.com